<?php
/**
 * @package    Eshoper/LPShipping/view/adminhtml/templates
 * @author     MB "Eshoper" <pagalba@eshoper.lt>
 * @copyright  AB Lietuvos paštas. All rights reserved.
 * @version    1.0.0
 * @since      File available since Release 1.0.0
 */

/** @var \Magento\Sales\Api\Data\OrderInterface $order */
$order = $block->getData ( 'order' );

$shippingMethod = $order->getShippingMethod ();

$sender = $block->getData ( 'sender' );

/** @var \Eshoper\LPShipping\Api\Data\CN22Interface|bool $CN22 */
$CN22 = $block->getData ( 'CN22' );

/** @var \Eshoper\LPShipping\Api\Data\CN23Interface|bool $CN23 */
$CN23 = $block->getData ( 'CN23' );

// Format CN22Parts Object
$CN22Parts = [];

// Default CN Parts
$CNPartsDefault = [];

foreach ( $block->getData ( 'order' )->getAllVisibleItems () as $item ) {
    $CNPartsDefault [] = ( object ) [
        'summary' => $item->getName (),
        'amount' => $item->getPrice (),
        'countryCode' => 'LT', // Default country of origin
        'currencyCode' => $block->getData ( 'order' )->getOrderCurrencyCode (),
        'hsCode' => '',
        'weight' => $item->getWeight () * 1000, // Weight in grams
        'quantity' => $item->getQtyOrdered ()
    ];
}

if ( !$CN22 || !$CN22->getCnParts () ) {
    $CN22Parts = $CNPartsDefault;
} else {
    $CN22Parts = json_decode ( $CN22->getCnParts () );
}

$CN23Parts = [];

if ( !$CN23 || !$CN23->getCnParts () ) {
    $CN23Parts = $CNPartsDefault;
} else {
    $CN23Parts = json_decode ( $CN23->getCnParts () );
}
?>
<div id="eshoper-lpshipping-shipment-modal" style="display: none">
    <form action="<?php echo $block->getData ( 'actionUrl' ); ?>" data-mage-init='{"validation": {}}'>
        <input type="hidden" name="order_id" value="<?php echo $order->getEntityId (); ?>" />
        <div class="lpshipping-shipment-nav" style="display: flex; border-bottom: 1px solid #e4e4e4;">
            <?php if ( $shippingMethod != 'lpcarrier_lpcarrierlpexpress_postoffice' ): ?>
                <div class="step active" data-tab="1" style="padding: 20px; padding-bottom: 0px;
                    border-right: 1px solid #e4e4e4;">
                    <h3><?php echo __( 'Parcel Information' ); ?></h3>
                </div>
            <?php endif; ?>
            <div class="step <?php echo $shippingMethod == 'lpcarrier_lpcarrierlpexpress_postoffice' ? 'active' : ''; ?>" data-tab="2" style="padding: 20px; padding-bottom: 0px;
                border-right: 1px solid #e4e4e4;">
                <h3><?php echo __( 'Sender Information' ); ?></h3>
            </div>
            <?php if ( $CN22 ): ?>
                <div class="step" data-tab="3" style="padding: 20px; padding-bottom: 0px;
                    border-right: 1px solid #e4e4e4;">
                    <h3><?php echo __( 'CN22 Declaration' ); ?></h3>
                </div>
            <?php endif; ?>
            <?php if ( $CN23 ): ?>
                <div class="step" data-tab="4" style="padding: 20px; padding-bottom: 0px;">
                    <h3><?php echo __( 'CN23 Declaration' ); ?></h3>
                </div>
            <?php endif; ?>
        </div>
        <div class="tab <?php echo $shippingMethod != 'lpcarrier_lpcarrierlpexpress_postoffice' ? 'tab-active' : ''; ?>" data-tab="1">
            <?php if ( $shippingMethod != 'lpcarrier_lpcarrierlp_postoffice'
                && $shippingMethod != 'lpcarrier_lpcarrierlp_overseas' ): // LPEXPRESS ?>
                <div style="border-bottom: 1px solid #e4e4e4; margin-top: 20px; padding-bottom: 20px">
                    <span><h2><?php echo __( 'Ship From:' ); ?></h2></span>
                    <ul class="lpshipping-list-shipfrom">
                        <li class="lpshipping-list-shipfrom-item">
                            <label class="lpshipping-list-shipfrom-item-label <?php echo $order->getLpShippingType () == 'HC' || $order->getLpShippingType () == 'EBIN' ? 'active' : ''; ?>">
                                <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/portable-post.svg' ); ?>" alt="">
                                <input type="radio" name="shipping_type" value="<?php echo $shippingMethod != 'lpcarrier_lpcarrierlpexpress_terminal' ? 'EBIN' : 'HC'; ?>"
                                    <?php echo $order->getLpShippingType () == 'HC' || $order->getLpShippingType () == 'EBIN' ? 'checked' : ''; ?> />
                                <span><?php echo __( 'LP EXPRESS Courier' ); ?></span>
                            </label>
                        </li>
                        <li class="lpshipping-list-shipfrom-item">
                            <label class="lpshipping-list-shipfrom-item-label <?php echo $order->getLpShippingType () == 'CC' || $order->getLpShippingType () == 'CHCA' ? 'active' : ''; ?>">
                                <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/parcel-terminal.svg' ); ?>" alt="">
                                <input type="radio" name="shipping_type" value="<?php echo $shippingMethod != 'lpcarrier_lpcarrierlpexpress_terminal' ? 'CHCA' : 'CC'; ?>"
                                    <?php echo $order->getLpShippingType () == 'CC' || $order->getLpShippingType () == 'CHCA' ? 'checked' : ''; ?> />
                                <span><?php echo __( 'LP EXPRESS Terminal' ); ?></span>
                            </label>
                        </li>
                    </ul>
                </div>
                <div style="display: flex; margin-top: 20px">
                    <div>
                        <span><h2><?php echo __( 'The Item Being Sent' ); ?></h2></span>
                        <ul class="lpshipping-list-sizes <?php echo $order->getLpShippingType () == 'EBIN' ? 'disabled' : ''; ?>">
                            <li class="lpshipping-list-sizes-item">
                                <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingSize () == 'XSmall' ? 'active' : ''; ?>">
                                    <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-1.svg' ); ?>" alt="">
                                    <input type="radio" name="shipping_size" value="XSmall" <?php echo $order->getLpShippingSize () == 'XSmall' ? 'checked' : ''; ?> />
                                    <span>XS - <?php echo __( 'to' ); ?> 30 kg</span>
                                    <span class="color-gray">185/610/80 mm</span>
                                </label>
                            </li>
                            <li class="lpshipping-list-sizes-item">
                                <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingSize () == 'Small' ? 'active' : ''; ?>">
                                    <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-2.svg' ); ?>" alt="">
                                    <input type="radio" name="shipping_size" value="Small" <?php echo $order->getLpShippingSize () == 'Small' ? 'checked' : ''; ?> />
                                    <span>S - <?php echo __( 'to' ); ?> 30 kg</span>
                                    <span class="color-gray">350/610/80 mm</span>
                                </label>
                            </li>
                            <li class="lpshipping-list-sizes-item">
                                <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingSize () == 'Medium' ? 'active' : ''; ?>">
                                    <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-3.svg' ); ?>" alt="">
                                    <input type="radio" name="shipping_size" value="Medium" <?php echo $order->getLpShippingSize () == 'Medium' ? 'checked' : ''; ?> />
                                    <span>M - <?php echo __( 'to' ); ?> 30 kg</span>
                                    <span class="color-gray">350/610/175 mm</span>
                                </label>
                            </li>
                            <li class="lpshipping-list-sizes-item">
                                <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingSize () == 'Large' ? 'active' : ''; ?>">
                                    <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-4.svg' ); ?>" alt="">
                                    <input type="radio" name="shipping_size" value="Large" <?php echo $order->getLpShippingSize () == 'Large' ? 'checked' : ''; ?> />
                                    <span>L - <?php echo __( 'to' ); ?> 30 kg</span>
                                    <span class="color-gray">350/610/365 mm</span>
                                </label>
                            </li>
                            <li class="lpshipping-list-sizes-item">
                                <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingSize () == 'XLarge' ? 'active' : ''; ?>">
                                    <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-5.svg' ); ?>" alt="">
                                    <input type="radio" name="shipping_size" value="XLarge" <?php echo $order->getLpShippingSize () == 'XLarge' ? 'checked' : ''; ?> />
                                    <span>XL - <?php echo __( 'to' ); ?> 30 kg</span>
                                    <span class="color-gray">350/610/745 mm</span>
                                </label>
                            </li>
                        </ul>
                    </div>
                </div>
            <?php else: // LP ?>
                <?php if ( $shippingMethod == 'lpcarrier_lpcarrierlp_postoffice' ): ?>
                    <div style="display: flex; margin-top: 20px">
                        <div style="width: 75%">
                            <span><h2><?php echo __( 'The Item Being Sent' ); ?></h2></span>
                            <ul class="lpshipping-list-sizes">
                                <li class="lpshipping-list-sizes-item">
                                    <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingType () == 'SMALL_CORESPONDENCE' ? 'active' : ''; ?>">
                                        <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-3.svg' ); ?>" alt="">
                                        <input type="radio" name="shipping_type" value="SMALL_CORESPONDENCE" />
                                        <span>S - <?php echo __( 'to' ); ?> 0.5 kg</span>
                                        <span class="color-gray">20/381/305 mm</span>
                                    </label>
                                </li>
                                <li class="lpshipping-list-sizes-item">
                                    <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingType () == 'BIG_CORESPONDENCE' ? 'active' : ''; ?>">
                                        <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-3.svg' ); ?>" alt="">
                                        <input type="radio" name="shipping_type" value="BIG_CORESPONDENCE"
                                            <?php echo $order->getLpShippingType () == 'BIG_CORESPONDENCE' ? 'checked' : ''; ?> />
                                        <span>M - <?php echo __( 'to' ); ?> 2 kg</span>
                                        <span class="color-gray">600/600/600 mm</span>
                                    </label>
                                </li>
                                <li class="lpshipping-list-sizes-item">
                                    <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingType () == 'PACKAGE' ? 'active' : ''; ?>">
                                        <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-3.svg' ); ?>" alt="">
                                        <input type="radio" name="shipping_type" value="PACKAGE"
                                            <?php echo $order->getLpShippingType () == 'PACKAGE' ? 'checked' : ''; ?> />
                                        <span>L - <?php echo __( 'to' ); ?> 30 kg</span>
                                        <span class="color-gray">2/1050/1050 mm</span>
                                    </label>
                                </li>
                            </ul>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ( $shippingMethod == 'lpcarrier_lpcarrierlp_overseas' ): // LP ?>
                    <div style="display: flex; margin-top: 20px">
                        <div style="width: 75%">
                            <span><h2><?php echo __( 'The Item Being Sent' ); ?></h2></span>
                            <ul class="lpshipping-list-sizes">
                                <li class="lpshipping-list-sizes-item">
                                    <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingType () == 'SMALL_CORESPONDENCE' ? 'active' : ''; ?>">
                                        <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-3.svg' ); ?>" alt="">
                                        <input type="radio" name="shipping_type" value="SMALL_CORESPONDENCE" />
                                        <span>S - <?php echo __( 'to' ); ?> 0.5 kg</span>
                                        <span class="color-gray">20/381/305 mm</span>
                                    </label>
                                </li>
                                <li class="lpshipping-list-sizes-item">
                                    <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingType () == 'BIG_CORESPONDENCE' ? 'active' : ''; ?>">
                                        <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-3.svg' ); ?>" alt="">
                                        <input type="radio" name="shipping_type" value="BIG_CORESPONDENCE"
                                            <?php echo $order->getLpShippingType () == 'BIG_CORESPONDENCE' ? 'checked' : ''; ?> />
                                        <span>M - <?php echo __( 'to' ); ?> 2 kg</span>
                                        <span class="color-gray">600/600/600 mm</span>
                                    </label>
                                </li>
                                <li class="lpshipping-list-sizes-item">
                                    <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingType () == 'PACKAGE' ? 'active' : ''; ?>">
                                        <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-3.svg' ); ?>" alt="">
                                        <input type="radio" name="shipping_type" value="PACKAGE"
                                            <?php echo $order->getLpShippingType () == 'PACKAGE' ? 'checked' : ''; ?> />
                                        <span>L - <?php echo __( 'to' ); ?> 30 kg</span>
                                        <span class="color-gray">2/1050/1050 mm</span>
                                    </label>
                                </li>
                                <li class="lpshipping-list-sizes-item">
                                    <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingType () == 'SMALL_CORESPONDENCE_TRACKED' ? 'active' : ''; ?>">
                                        <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-3.svg' ); ?>" alt="">
                                        <input type="radio" name="shipping_type" value="SMALL_CORESPONDENCE_TRACKED"
                                            <?php echo $order->getLpShippingType () == 'SMALL_CORESPONDENCE_TRACKED' ? 'checked' : ''; ?> />
                                        <span>S_TRACKED</span>
                                        <span class="color-gray"><?php echo __( 'To' ); ?> 500 g</span>
                                    </label>
                                </li>
                                <li class="lpshipping-list-sizes-item">
                                    <label class="lpshipping-list-sizes-item-size <?php echo $order->getLpShippingType () == 'MEDIUM_CORESPONDENCE_TRACKED' ? 'active' : ''; ?>">
                                        <img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/box-type-3.svg' ); ?>" alt="">
                                        <input type="radio" name="shipping_type" value="MEDIUM_CORESPONDENCE_TRACKED"
                                            <?php echo $order->getLpShippingType () == 'MEDIUM_CORESPONDENCE_TRACKED' ? 'checked' : ''; ?> />
                                        <span>M_TRACKED</span>
                                        <span class="color-gray"><?php echo __( 'To' ); ?> 2 kg</span>
                                    </label>
                                </li>
                            </ul>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
            <div class="additional-options">
                <div class="admin__field">
                    <?php if ( $order->getPayment ()->getMethod () === 'cashondelivery' ): ?>
                        <label style="margin-left: 10px" class="admin__field-label">COD (&euro;):
                            <input type="number" step="0.01"
                                   value="<?php echo number_format ( $order->getLpCod () ?? $order->getGrandTotal (), 2); ?>"
                                   min="0.00" class="admin__control-text" name="cod"
                                   data-validate='{"required":true}' />
                        </label>
                    <?php endif; ?>
                </div>
            </div>
            <?php if ( $shippingMethod == 'lpcarrier_lpcarrierlpexpress_terminal' ): ?>
                <div style="display: flex;">
                    <div style="width: 75%">
                        <span><h2><?php echo __( 'Ship To:' ); ?></h2></span>
                        <div class="admin__field-control">
                            <b>Terminal:</b> <select name="terminal_id" class="admin__control-select">
                                <?php foreach ( array_reverse ( $block->getData ( 'terminals' ) ) as $city => $terminals ): ?>
                                    <optgroup label="<?php echo $city; ?>">
                                        <?php foreach ( $terminals as $terminalId => $terminal ): ?>
                                            <option value="<?php echo $terminalId; ?>" <?php echo $order->getLpexpressTerminal () == $terminalId ? 'selected' : ''; ?>>
                                                <?php echo $terminal; ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </optgroup>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- Sender info -->
        <div class="tab <?php echo $shippingMethod == 'lpcarrier_lpcarrierlpexpress_postoffice' ? 'tab-active' : ''; ?>" data-tab="2" style="margin-top: 20px">
            <h2><?php echo __( 'Sender Information' ); ?></h2>
            <div class="admin__field">
                <label for="sender_name" class="admin__field-label">
                    <?php echo __('Name'); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <input name="sender[sender_name]"
                           id="sender_name" class="admin__control-text" value="<?php echo htmlentities ( $sender [ 'name' ] ); ?>"
                           data-validate='{"required":true}' />
                </div>
            </div>
            <div class="admin__field">
                <label for="sender_phone" class="admin__field-label">
                    <?php echo __('Phone'); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <input name="sender[sender_phone]"
                           id="sender_phone" class="admin__control-text" value="<?php echo $sender [ 'phone' ]; ?>"
                           data-validate='{"required":true}' />
                </div>
            </div>
            <div class="admin__field">
                <label for="sender_email" class="admin__field-label">
                    <?php echo __('Email'); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <input type="email" name="sender[sender_email]"
                           id="sender_email" class="admin__control-text" value="<?php echo $sender [ 'email' ]; ?>"
                           data-validate='{"required":true}' />
                </div>
            </div>
            <div class="admin__field">
                <label for="sender_country" class="admin__field-label">
                    <?php echo __('Country'); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <select name="sender[sender_country]" id="sender_country" class="admin__control-select">
                        <?php foreach ( $block->getData ( 'countries' )->toOptionArray () as $country ): ?>
                                <option value="<?php echo $country [ 'value' ]; ?>" <?php echo $country [ 'value' ] === $sender [ 'country' ] ? 'selected' : ''; ?>>
                                    <?php echo $country [ 'label' ]; ?>
                                </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="admin__field">
                <label for="sender_city" class="admin__field-label">
                    <?php echo __('City'); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <input type="text" name="sender[sender_city]" value="<?php echo $sender [ 'city' ]; ?>"
                           id="sender_city" class="admin__control-text"
                           data-validate='{"required":true}' />
                </div>
            </div>
            <div class="admin__field">
                <label for="sender_street" class="admin__field-label">
                    <?php echo __('Street'); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <input type="text" name="sender[sender_street]" value="<?php echo $sender [ 'street' ]; ?>"
                           id="sender_street" class="admin__control-text"
                           data-validate='{"required":true}' />
                </div>
            </div>
            <div class="admin__field">
                <label for="sender_building" class="admin__field-label">
                    <?php echo __('Building Number'); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <input type="text" name="sender[sender_building]" value="<?php echo $sender [ 'building' ]; ?>"
                           id="sender_building" class="admin__control-text"
                           data-validate='{"required":true}' />
                </div>
            </div>
            <div class="admin__field">
                <label for="sender_apartment" class="admin__field-label">
                    <?php echo __('Apartment'); ?>
                </label>
                <div class="admin__field-control">
                    <input type="text" name="sender[sender_apartment]" value="<?php echo $sender [ 'apartment' ]; ?>"
                           id="sender_apartment" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="sender_postcode" class="admin__field-label">
                    <?php echo __('Post Code'); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <input type="text" name="sender[sender_postcode]" value="<?php echo $sender [ 'postcode' ]; ?>"
                           id="sender_postcode" class="admin__control-text"
                           data-validate='{"required":true}' />
                </div>
            </div>
        </div>
        <?php if ( $CN22 ): ?>
            <div class="tab" data-tab="3" style="margin-top: 20px;">
            <h2><?php echo __( 'CN22 Declaration' ); ?></h2>
            <div class="admin__field">
                <label for="parcel_type" class="admin__field-label">
                    <?php echo __( 'Parcel Type' ); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <select name="cn22[parcel_type]" id="parcel_type" class="admin__control-select">
                        <option value="Sell">Sell</option>
                        <option value="Gift" <?php echo $CN22->getParcelType () == 'Gift' ? 'selected' : ''; ?>>Gift</option>
                        <option value="Document" <?php echo $CN22->getParcelType () == 'Document' ? 'selected' : ''; ?>>Document</option>
                        <option value="Sample" <?php echo $CN22->getParcelType () == 'Sample' ? 'selected' : ''; ?>>Sample</option>
                        <option value="Return" <?php echo $CN22->getParcelType () == 'Return' ? 'selected' : ''; ?>>Return</option>
                        <option value="Other" <?php echo $CN22->getParcelType () == 'Other' ? 'selected' : ''; ?>>Other</option>
                    </select>
                </div>
            </div>
            <div class="admin__field">
                <label for="parcel_type_notes" class="admin__field-label">
                    <?php echo __('Parcel Type Notes'); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <input name="cn22[parcel_type_notes]"
                           value="<?php echo $CN22->getParcelTypeNotes () ?: 'Sell Items'; ?>"
                           id="parcel_type_notes" class="admin__control-text"
                           data-validate='{"required":true}' />
                </div>
            </div>
            <div class="admin__field">
                <label for="parcel_description" class="admin__field-label">
                    <?php echo __('Parcel Description'); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                <textarea name="cn22[parcel_description]" id="parcel_description"
                          class="admin__control-textarea"
                          data-validate='{"required":true}'><?php echo $CN22->getParcelDescription () ?: 'Sell'; ?></textarea>
                </div>
            </div>
            <section class="admin__page-section">
                <div class="admin__page-section-title">
                    <span class="title"><?php echo __( 'Parcel Items' ) ?></span>
                </div>
                <div class="admin__table-wrapper">
                    <table class="data-table admin__table-primary edit-order-table">
                        <thead>
                        <tr class="headings">
                            <th class="col-summary">
                            <span>
                                <?php echo __( 'Summary' ); ?> <span style="color:red">*</span>
                            </span>
                            </th>
                            <th class="col-amount">
                            <span>
                                <?php echo __( 'Amount' ); ?> <span style="color:red">*</span>
                            </span>
                            </th>
                            <th class="col-country">
                            <span>
                                <?php echo __( 'Country of Origin' ); ?> <span style="color:red">*</span>
                            </span>
                            </th>
                            <th class="col-currency">
                            <span>
                                <?php echo __( 'Currency' ); ?> <span style="color:red">*</span>
                            </span>
                            </th>
                            <th class="col-hs-code">
                                <span><?php echo __( 'HS Item Number' ); ?></span>
                            </th>
                            <th class="col-weight">
                            <span>
                                <?php echo __( 'Weight' ); ?> (g) <span style="color:red">*</span>
                            </span>
                            </th>
                            <th class="col-quantity">
                            <span>
                                <?php echo __( 'Quantity' ); ?> <span style="color:red">*</span>
                            </span>
                            </th>
                        </tr>
                        </thead>
                        <tbody class="even">
                        <?php /* @var \Magento\Catalog\Model\Product $item */ ?>
                        <?php $counter = -1; foreach ( $CN22Parts as $item ): $counter++; ?>
                            <tr>
                                <td class="col-summary">
                                    <div class="admin__field-control">
                                        <input name="cn22[items][<?php echo $counter; ?>][summary]]" type="text" id="summary"
                                               class="admin__control-text" value="<?php echo $item->summary; ?>"
                                               data-validate='{"required":true}' />
                                    </div>
                                </td>
                                <td class="col-amount">
                                    <div class="admin__field-control">
                                        <input name="cn22[items][<?php echo $counter; ?>][amount]" type="number"
                                               value="<?php echo number_format ( $item->amount, 2 ); ?>"
                                               step="0.01" id="amount" class="admin__control-text"
                                               data-validate='{"required":true}' />
                                    </div>
                                </td>
                                <td class="col-country" style="max-width: 155px">
                                    <select name="cn22[items][<?php echo $counter; ?>][countryCode]" id="countryCode" class="admin__control-select">
                                        <?php foreach ( $block->getData ( 'countries' )->availableCountries () as $country ): ?>
                                                <option value="<?php echo $country [ 'value' ] ?>" <?php echo $country [ 'value' ] === 'LT' ? 'selected' : ''; ?>>
                                                    <?php echo $country [ 'label' ]; ?>
                                                </option>
                                        <?php endforeach; ?>
                                    </select>
                                </td>
                                <td class="col-currency">
                                    <select name="cn22[items][<?php echo $counter; ?>][currencyCode]" id="currencyCode" class="admin__control-select">
                                        <option value="EUR">EUR</option>
                                        <option value="USD" <?php echo $item->currencyCode
                                        == 'USD' ? 'selected' : ''; ?>>USD</option>
                                    </select>
                                </td>
                                <td class="col-hs-code">
                                    <div class="admin__field-control">
                                        <input name="cn22[items][<?php echo $counter; ?>][hsCode]" id="hscode"
                                               value="<?php echo $item->hsCode; ?>" class="admin__control-text" />
                                    </div>
                                </td>
                                <td class="col-weight">
                                    <div class="admin__field-control">
                                        <input name="cn22[items][<?php echo $counter; ?>][weight]" type="number" value="<?php echo $item->weight; ?>"
                                               step="0.01" id="weight" class="admin__control-text"
                                               data-validate='{"required":true}' />
                                    </div>
                                </td>
                                <td class="col-quantity">
                                    <div class="admin__field-control">
                                        <input name="cn22[items][<?php echo $counter; ?>][quantity]" type="number"
                                               value="<?php echo intval ( $item->quantity ); ?>"
                                               step="1" id="quantity" class="admin__control-text"
                                               data-validate='{"required":true}'>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </section>
        </div>
        <?php endif; ?>
        <?php if ( $CN23 ): ?>
            <div class="tab" data-tab="4" style="margin-top: 20px">
            <h2><?php echo __( 'CN23 Declaration' ); ?></h2>
            <div class="admin__field">
                <label for="parcel_type" class="admin__field-label">
                    <?php echo __( 'Parcel Type' ); ?> <span style="color:red">*</span>
                </label>
                <div class="admin__field-control">
                    <select name="cn23[parcel_type]" id="parcel_type" class="admin__control-select">
                        <option value="Sell">Sell</option>
                        <option value="Gift" <?php echo $CN23->getParcelType () == 'Gift' ? 'selected' : ''; ?>>Gift</option>
                        <option value="Document" <?php echo $CN23->getParcelType () == 'Document' ? 'selected' : ''; ?>>Document</option>
                        <option value="Sample" <?php echo $CN23->getParcelType () == 'Sample' ? 'selected' : ''; ?>>Sample</option>
                        <option value="Return" <?php echo $CN23->getParcelType () == 'Return' ? 'selected' : ''; ?>>Return</option>
                        <option value="Other" <?php echo $CN23->getParcelType () == 'Other' ? 'selected' : ''; ?>>Other</option>
                    </select>
                </div>
            </div>
            <div class="admin__field">
                <label for="parcel_type_notes" class="admin__field-label">
                    <?php echo __('Parcel Type Notes'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[parcel_type_notes]"
                           value="<?php echo $CN23->getParcelTypeNotes () ?: 'Sell Items'; ?>"
                           id="parcel_type_notes" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="exporter_customs_code" class="admin__field-label">
                    <?php echo __('Exporter Customs Code'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[exporter_customs_code]"
                           value="<?php echo $CN23->getExporterCustomsCode(); ?>"
                           id="exporter_customs_code" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="license" class="admin__field-label">
                    <?php echo __('License'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[license]"
                           value="<?php echo $CN23->getLicense (); ?>"
                           id="license" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="certificate" class="admin__field-label">
                    <?php echo __('Certificate'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[certificate]"
                           value="<?php echo $CN23->getCertificate (); ?>"
                           id="certificate" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="invoice" class="admin__field-label">
                    <?php echo __('Invoice'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[invoice]"
                           value="<?php echo $CN23->getInvoice (); ?>"
                           id="invoice" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="invoice" class="admin__field-label">
                    <?php echo __('Notes'); ?>
                </label>
                <div class="admin__field-control">
                <textarea name="cn23[notes]" id="parcel_description"
                          class="admin__control-textarea"><?php echo $CN23->getNotes (); ?></textarea>
                </div>
            </div>
            <div class="admin__field">
                <label for="faiilure_instructions" class="admin__field-label">
                    <?php echo __('Failure Instruction'); ?>
                </label>
                <div class="admin__field-control">
                    <select name="cn23[failure_instruction]" id="parcel_type" class="admin__control-select">
                        <option value="RETURN_TO_SENDER_NON_PRIORITY"
                            <?php echo $CN23->getFailureInstruction () == 'RETURN_TO_SENDER_NON_PRIORITY' ? 'selected' : ''; ?>
                        >RETURN_TO_SENDER_NON_PRIORITY</option>
                        <option value="RETURN_TO_SENDER_PRIORITY"
                            <?php echo $CN23->getFailureInstruction () == 'RETURN_TO_SENDER_PRIORITY' ? 'selected' : ''; ?>
                        >RETURN_TO_SENDER_PRIORITY</option>
                        <option value="TREAT_AS_ABANDONED"
                            <?php echo $CN23->getFailureInstruction () == 'TREAT_AS_ABANDONED' ? 'selected' : ''; ?>
                        >TREAT_AS_ABANDONED</option>
                    </select>
                </div>
            </div>
            <div class="admin__field">
                <label for="importer_code" class="admin__field-label">
                    <?php echo __('Importer Code'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[importer_code]"
                           value="<?php echo $CN23->getImporterCode (); ?>"
                           id="importer_code" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="importer_customs_code" class="admin__field-label">
                    <?php echo __('Importer Customs Code'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[importer_customs_code]"
                           value="<?php echo $CN23->getImporterCustomsCode (); ?>"
                           id="importer_customs_code" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="importer_email" class="admin__field-label">
                    <?php echo __('Importer Email'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[importer_email]"
                           value="<?php echo $CN23->getImporterEmail (); ?>"
                           id="importer_email" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="importer_fax" class="admin__field-label">
                    <?php echo __('Importer Fax'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[importer_fax]"
                           value="<?php echo $CN23->getImporterFax (); ?>"
                           id="importer_fax" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="importer_phone" class="admin__field-label">
                    <?php echo __('Importer Phone'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[importer_phone]"
                           value="<?php echo $CN23->getImporterPhone (); ?>"
                           id="importer_phone" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="importer_tax_code" class="admin__field-label">
                    <?php echo __('Importer Tax Code'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[importer_tax_code]"
                           value="<?php echo $CN23->getImporterTaxCode (); ?>"
                           id="importer_tax_code" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="importer_vat_code" class="admin__field-label">
                    <?php echo __('Importer Vat Code'); ?>
                </label>
                <div class="admin__field-control">
                    <input name="cn23[importer_vat_code]"
                           value="<?php echo $CN23->getImporterVatCode (); ?>"
                           id="importer_vat_code" class="admin__control-text" />
                </div>
            </div>
            <div class="admin__field">
                <label for="description" class="admin__field-label">
                    <?php echo __( 'Description' ); ?>
                </label>
                <div class="admin__field-control">
                <textarea name="cn23[description]" id="description"
                          class="admin__control-textarea"><?php echo $CN23->getDescription(); ?></textarea>
                </div>
            </div>
            <section class="admin__page-section">
                <div class="admin__page-section-title">
                    <span class="title"><?php echo __( 'Parcel Items' ) ?></span>
                </div>
                <div class="admin__table-wrapper">
                    <table class="data-table admin__table-primary edit-order-table">
                        <thead>
                        <tr class="headings">
                            <th class="col-summary">
                            <span>
                                <?php echo __( 'Summary' ); ?> <span style="color:red">*</span>
                            </span>
                            </th>
                            <th class="col-amount">
                            <span>
                                <?php echo __( 'Amount' ); ?> <span style="color:red">*</span>
                            </span>
                            </th>
                            <th class="col-country">
                            <span>
                                <?php echo __( 'Country of Origin' ); ?> <span style="color:red">*</span>
                            </span>
                            </th>
                            <th class="col-currency">
                            <span>
                                <?php echo __( 'Currency' ); ?> <span style="color:red">*</span>
                            </span>
                            </th>
                            <th class="col-hs-code">
                                <span><?php echo __( 'HS Item Number' ); ?></span>
                            </th>
                            <th class="col-weight">
                            <span>
                                <?php echo __( 'Weight' ); ?> (g) <span style="color:red">*</span>
                            </span>
                            </th>
                            <th class="col-quantity">
                            <span>
                                <?php echo __( 'Quantity' ); ?> <span style="color:red">*</span>
                            </span>
                            </th>
                        </tr>
                        </thead>
                        <tbody class="even">
                        <?php /* @var \Magento\Catalog\Model\Product $item */ ?>
                        <?php $counter = -1; foreach ( $CN23Parts as $item ): $counter++; ?>
                            <tr>
                                <td class="col-summary">
                                    <div class="admin__field-control">
                                        <input name="cn23[items][<?php echo $counter; ?>][summary]" type="text" id="summary"
                                               class="admin__control-text" value="<?php echo $item->summary; ?>"
                                               data-validate='{"required":true}' />
                                    </div>
                                </td>
                                <td class="col-amount">
                                    <div class="admin__field-control">
                                        <input name="cn23[items][<?php echo $counter; ?>][amount]" type="number"
                                               value="<?php echo number_format ( $item->amount, 2 ); ?>"
                                               step="0.01" id="amount" class="admin__control-text"
                                               data-validate='{"required":true}' />
                                    </div>
                                </td>
                                <td class="col-country" style="max-width: 155px">
                                    <select name="cn23[items][<?php echo $counter; ?>][countryCode]" id="countryCode" class="admin__control-select">
                                        <?php foreach ( $block->getData ( 'countries' )->availableCountries () as $country ): ?>
                                                <option <?php echo $country [ 'value' ] === 'LT' ? 'selected' : ''; ?>
                                                        value="<?php echo $country [ 'value' ] ?>">
                                                    <?php echo $country [ 'label' ] ?>
                                                </option>
                                        <?php endforeach; ?>
                                    </select>
                                </td>
                                <td class="col-currency">
                                    <select name="cn23[items][<?php echo $counter; ?>][currencyCode]" id="currencyCode" class="admin__control-select">
                                        <option value="EUR">EUR</option>
                                        <option value="USD" <?php echo $item->currencyCode
                                        == 'USD' ? 'selected' : ''; ?>>USD</option>
                                    </select>
                                </td>
                                <td class="col-hs-code">
                                    <div class="admin__field-control">
                                        <input name="cn23[items][<?php echo $counter; ?>][hsCode]" id="hscode"
                                               value="<?php echo $item->hsCode; ?>" class="admin__control-text" />
                                    </div>
                                </td>
                                <td class="col-weight">
                                    <div class="admin__field-control">
                                        <input name="cn23[items][<?php echo $counter; ?>][weight]" type="number" value="<?php echo $item->weight; ?>"
                                               step="0.01" id="weight" class="admin__control-text"
                                               data-validate='{"required":true}' />
                                    </div>
                                </td>
                                <td class="col-quantity">
                                    <div class="admin__field-control">
                                        <input name="cn23[items][<?php echo $counter; ?>][quantity]" type="number"
                                               value="<?php echo intval ( $item->quantity ); ?>"
                                               step="1" id="quantity" class="admin__control-text"
                                               data-validate='{"required":true}'>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </section>
        </div>
        <?php endif; ?>
    </form>
</div>


<script>
    let Eshoper_LPShipping_Shipment_Modal = null;
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function (
            $,
            modal
        ) {
            let options = {
                type: 'slide',
                responsive: true,
                innerScroll: true,
                title: '<div style="display:flex; align-items:center;">' +
                    '<img src="<?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/logo.svg' ); ?>" /> &nbsp;' + $.mage.__('Shipment Details') + '</div>',
                modalClass: 'eshoper-lpshipping-shipment-modal',
                buttons: [
                    {
                        text: $.mage.__('Close'),
                        click: function () {
                            this.closeModal();
                        }
                    },
                    {
                        text: $.mage.__('Save'),
                        class: 'action action-primary lpbutton-noicon lpaction-save',
                        click: function () {
                            let shipmentForm = $('#eshoper-lpshipping-shipment-modal form');
                            shipmentForm.append($('<input>', {
                                'name': 'form_key',
                                'value': window.FORM_KEY,
                                'type': 'hidden'
                            }));
                            shipmentForm.submit ();
                        }
                    }
                ]
            };

            modal(options, $('#eshoper-lpshipping-shipment-modal'));

            Eshoper_LPShipping_Shipment_Modal = $ ("#eshoper-lpshipping-shipment-modal");

            $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-list-sizes-item-size' ).on ( 'click', function () {
                $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-list-sizes-item-size.active' ).removeClass ( 'active' );
                $ ( this ).addClass ( 'active' );
            });

            $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-list-shipfrom-item-label' ).on ( 'click', function () {
                $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-list-shipfrom-item-label.active' ).removeClass ( 'active' );
                $ ( this ).addClass ( 'active' );

                if ( $ ( this ).children ( 'input' ).val () === "EBIN" ) {
                    $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-list-sizes' ).addClass ( 'disabled' );
                    $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-list-sizes-item-size.active' ).removeClass ( 'active' );
                    $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-list-sizes input' ).prop ( 'checked', false );
                } else {
                    $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-list-sizes' ).removeClass ( 'disabled' );
                    $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-list-sizes input[value="<?php echo $order->getLpShippingSize (); ?>"]')
                        .prop ( 'checked', true ).parent ().addClass ( 'active' );
                }
            });

            $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-shipment-nav .step' ).on ( 'click', function () {
                $ ( '#eshoper-lpshipping-shipment-modal .lpshipping-shipment-nav .step' ).removeClass ( 'active' );
                $ ( this ).addClass ( 'active' );

                $ ( '#eshoper-lpshipping-shipment-modal .tab').removeClass ( 'tab-active' );
                $ ( '#eshoper-lpshipping-shipment-modal .tab[data-tab="' + $ ( this ).data ( 'tab' ) + '"]' ).addClass ( 'tab-active' );
            });
        }
    );
</script>
<style>
    .lpshipping-list-sizes.disabled .lpshipping-list-sizes-item-size {
        pointer-events: none;
        opacity: 0.6;
    }

    .lpbutton, .lpbutton-noicon {
        color: black !important;
        border-color: black !important;
        background-color: #ffdd00 !important;
    }

    .lpbutton.hidden {
        display: none !important;
    }

    .lpbutton span:before {
        content: "";
        display: inline-block;
        background: #ffdd00 url(
            <?php echo $this->getViewFileUrl ( 'Eshoper_LPShipping::images/icon.png' ); ?>
        ) no-repeat;
        width: 30px;
        background-size: contain;
        height: 20px;
        position: relative;
        top: 5px;
    }

    .lpbutton:after {
        border-color: #000000 transparent transparent transparent !important;
    }

    .eshoper-lpshipping-shipment-modal {
        width: 70%;
        left: inherit;
        right: 0;
    }

    .lpshipping-list-sizes, .lpshipping-list-shipfrom {
        display: flex;
        flex-wrap: wrap;
    }

    .lpshipping-list-sizes-item, .lpshipping-list-shipfrom-item {
        list-style: none;
    }

    .lpshipping-list-sizes-item-size, .lpshipping-list-shipfrom-item-label {
        vertical-align: middle;
        padding: 15px;
        cursor: pointer;
        position: relative;
        background-color: #f5f5f5;
        box-shadow: 0 1px 0 0 #ccc;
        border-radius: 3px;
        max-width: 145px;
        display: flex;
        flex-wrap: wrap;
        min-height: 110px;
        min-width: 145px;
        margin-right: 10px;
        margin-top: 10px;
    }

    .lpshipping-list-sizes-item-size:hover, .lpshipping-list-sizes-item-size.active,
       .lpshipping-list-shipfrom-item-label:hover, .lpshipping-list-shipfrom-item-label.active {
        background-color: #fcde05;
        box-shadow: 0 1px 0 0 #e3c905;
    }

    .lpshipping-shipment-nav .step.active {
        background-color: #fcde05;
        box-shadow: 0 1px 0 0 #e3c905;
    }

    .lpshipping-list-sizes-item-size span, .lpshipping-list-shipfrom-item-label span {
        width: 100%;
    }

    .lpshipping-list-sizes-item-size img, .lpshipping-list-shipfrom-item-label img {
        padding-bottom: 10px;
    }

    .lpshipping-list-sizes-item-size input, .lpshipping-list-shipfrom-item-label input {
        display: none;
    }

    .color-gray {
        color: gray;
    }

    .additional-options {
        border-top: 1px solid #e4e4e4;
        margin-top: 20px;
        padding: 20px 0px 20px 0px;
    }

    .lpshipping-shipment-nav .step {
        cursor: pointer;
    }

    #eshoper-lpshipping-shipment-modal .tab {
        display: none;
    }

    #eshoper-lpshipping-shipment-modal .tab.tab-active {
        display: block;
    }
</style>
