<?php
/**
 * @package    Eshoper/LPShipping/view/adminhtml/templates
 * @author     MB "Eshoper" <pagalba@eshoper.lt>
 * @copyright  AB Lietuvos paštas. All rights reserved.
 * @version    1.0.0
 * @since      File available since Release 1.0.0
 */
?>
<div id="lpexpress-block">
    <strong><?=$block->getMethodName () ?></strong>
    <span class="price"><?=$block->getMethodInfo() ?></span>
</div>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            var element = $('#lpexpress-block').detach();
            $('.order-shipping-method').append(element);
        }
    );
</script>
